##############################
# Please edit this line to "not_sample_anymore" to make the bot run
is_example_config_or_not: "Ahhhhhhhhhhh I am not blind so I'll follow what the line above me asked"
##############################
bot_token: "" # Bot Token
api_id: 0 # Get from my.telegram.org
api_hash: "" # Get from my.telegram.org
owner_id: 123456 # Owner's Telegram account ID
message_dump: 0 # Chat ID for Message Dump
load: [] # Modules to load (will load all if empty)
no_load: [] # Modules to exclude from loading
strict_antispam: False # Enforce Gbans
workers: 4 # Worker count
del_cmds: False # Delete admin commands executed by non-admins
spamwatch_api: '' # SpamWatch API Key

# Database
database_url: "postgres://username:password@host:5432/database_name" # Database URL

# Permissions
sudo_users: [] # List of the Telegram IDs of sudo users
whitelist_users: [] # List of the Telegram IDs of whitelisted users
